spring:
  application:
    name: shop-service
  profiles:
    active: main
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: mysql, eureka, actuator
      profile: local
server:
  port: 10300
